### ISSUE TITLE
Unable to create driver instance in 1st attempt with retry timeout of 60 seconds.

### ISSUE THREAD

**Issue by rafeekabid** [vaibhav2903/QuantumExperitestSample#1]
Hi Team,
I am getting Driver intialization issue whne tried to integrate quantum framework with experitest. I just downloaded the sample master code(Eribank automation code). I am getting bwloe issue when tried to run testng.appium.xml.

[RemoteTestNG] detected TestNG version 6.10.0
main: ISFW build info: {qaf-Type=core, qaf-Revision=15, qaf-Version=2.1, qaf-Build-Time=20-Nov-2019 22:28:06} 
main: Resource dir: D:\ExperiwithQuantum\QuantumExperitestSample-master\src\main\resources\common. Found property files to load: 0 
main: Resource dir: D:\ExperiwithQuantum\QuantumExperitestSample-master\src\main\resources\common. Found property files to load: 1 
include groups [@appium]
 exclude groups: [] Scanarios location: src/main/resources/scenarios 
log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.step.client.gherkin.GherkinScenarioFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
TestNG: â–ˆâ–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–€â–ˆ
TestNG: â–ˆ TEST STARTED: Login Test Flow â–ˆ
TestNG: â–ˆâ–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–„â–ˆ
TestNG: â–„ â–„ â–„ BEGIN STEP: Given User is already on Login Page â–„ â–„ â–„
TestNG: Initializing Driver...browser_str:appiumDriver,base_url:,sel_server:https://uscloud.experitest.com/wd/hub,port:443 
TestNG: Driver: appiumDriver 
TestNG: Direct Driver Connect 
_[35m[Appium]_[39m Welcome to Appium v1.17.1
_[35m[Appium]_[39m Appium REST http interface listener started on 0.0.0.0:4723
com.qmetry.qaf.automation.core.AutomationError: Unable to Create Driver Instance for appium: java.net.MalformedURLException: no protocol: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MDB22LT526', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: unknown
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.standardConnect(UiDriverFactory.java:441)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:412)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$300(UiDriverFactory.java:282)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:221)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:86)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:556)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at com.qmetry.qaf.automation.ui.util.DynamicWait.until(DynamicWait.java:148)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:466)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:246)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:44)
	at com.quantum.utils.DriverUtils.getDriver(DriverUtils.java:51)
	at com.quantum.utils.DriverUtils.getAppiumDriver(DriverUtils.java:35)
	at com.quantum.steps.EriBankLoginTestStepDefs.userAlreadyOnLoginPage(EriBankLoginTestStepDefs.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:146)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:126)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: java.net.MalformedURLException: no protocol: 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MDB22LT526', ip: '192.168.1.5', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: unknown
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:271)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.access$800(UiDriverFactory.java:70)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.standardConnect(UiDriverFactory.java:436)
	... 42 more
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:610)
	at java.net.URL.<init>(URL.java:507)
	at java.net.URL.<init>(URL.java:456)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:261)
	... 44 more
**Unable to create driver instance in 1st attempt with retry timeout of 120 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure.com/thoughtworks/selenium/CommandProcessor**
TestNG: â–€ â–€ â–€ END STEP: Given User is already on Login Page â–€ â–€ â–€

@vaibhav2903

**Comment by vaibhav2903** [comment]
Hi @rafeekabid , When you are running the test on your IDE, do you see the test in queue? If not, this might be related to connection problems while connecting from IDE to the cloud. Also, have you provided the correct URL and the access key in the properties file? Please check.

**Comment by rafeekabid** [comment]
Hi @vaibhav2903 ,
Tests are not in queue when run the scripts. I just modified in application property file with my details and didn’t change anything from other files. Kindly refer the below parameters has been changed.

remote.server=https://uscloud.experitest.com/wd/hub
remote.port= 443
driver.name=appiumDriver
appium.capabilities.accessKey=*****************My security key **************
appium.capabilities.deviceQuery=@os='ios' and @category='PHONE' and @serialnumber='2365d189babe4cc06a66ad9242fb6ee72ef1b253'
appium.capabilities.bundleId=com.experitest.ExperiBank
appium.capabilities.driverClass=io.appium.java_client.ios.IOSDriver

Note: I used same server url and accesskey for many other experitest automation which is working(without quantum framework ).
Kindly check and revert me your suggestions.

**Comment by vaibhav2903** [comment]
Fixed after upgrading to 1.21.2 version of quantum. Thanks!
